<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <RootNamespace>Microsoft.Azure.ApiManagement.PolicyToolkit.Tests.Decompiling</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MSTest" Version="3.11.1"/>
        <PackageReference Include="coverlet.collector" Version="6.0.4"/>
        <PackageReference Include="FluentAssertions" Version="7.0.0"/>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4"/>
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.3.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Authoring\Authoring.csproj"/>
        <ProjectReference Include="..\..\src\Core\Core.csproj"/>
        <ProjectReference Include="..\..\src\Decompiling\Decompiling.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="TestData\**\*.xml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
